spring.datasource.url=jdbc:mysql://localhost:3307/internships
spring.datasource.username=username=your_username
spring.datasource.password=password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# Custom config for tickets
internships.auto-publish=false

candidates.visible-by-default=true
